### PR TITLE
Add Spigot item_damage event

### PR DESCRIPTION
**Pull request by jacobwgillespie**
I haven't had a chance to test this in detail yet, but this first implementation should add support for the `item_damage` event.  I'll report back on testing shortly...

### CODE REVIEW

**Comment by PseudoKnight** [comment]
Needs a Listener to trigger the CH event, and a Bindable event to pass to it. This part seems to be good, though.

**Comment by jacobwgillespie** [comment]
Okay, I think this implements the event abstraction and listener - I tried to mirror the structure found in CommandHelper for consistency's sake.  Still need to officially test.  :)

**Comment by jacobwgillespie** [comment]
Yeah, this is a little bit messy - ignore this for now, will clean :)

**Comment by PseudoKnight** [comment]
Ya, that looks good. All I see right now is that you need to refer to MCItemDamageEvent in the Events. Then testing.

**Comment by jacobwgillespie** [comment]
Okay, this has been tested and works with a one major caveat: increasing the damage taken works just fine, however canceling the event or modifying the damage taken to 0 is not understood by the client.  So tools will continue to wear down on the client and will eventually "break", but if you at any time force a refresh by disconnecting and reconnecting, the item will appear again untouched.  There may be some way to force the client to refresh, but I haven't found it yet.  On the plus side, it's easier to hook into this event than others for making things unbreakable - this works at the moment:

```php
proc(_repair_item, @player, @slot) {
  @item = pinv(@player, @slot);
  @item['data'] = 0;
  @inv = array();
  @inv[@slot] = @item;
  set_pinv(@player, @inv);
}

# workaround because null slot is currently broken
proc(_repair_current_item, @player) {
  @slot = pinfo(@player, 15)
  _repair_item(@player, @slot)
}

bind(item_damage, null, null, @event) {
  _repair_current_item(@event['player'])
}
```

Maybe there's a way to do this in the Java here?  I'm just not too familiar with Spigot internals...

**Comment by PseudoKnight** [comment]
You're going to have to use the updateInventory() method in the Player class for both cancel() and modifyEvent(). 

Some minor notes:
- Line 145 should be ItemDamageEvent.
- Also, you have an extra "return true;" on line 112.
- Description for item "An item array representing the item being picked up" should probably be "An item array of the item being damaged".

**Comment by jacobwgillespie** [comment]
It works!!!  :)  Thanks for the help, the `updateInventory()` does the trick.

**Pull request merged**
